#!/bin/bash
  
# This is a script to build a clean set of SIG/M volumes from available sources.
  
# --------
# VERSIONS
# --------
#   The latest version of this script is available at https://github.com/CPMArchives/SIGM.
#
#   2022-04-06 - Set date of ARK, LBR, DSK dirs to release date of vol 310.
#   
#   2022-04-05 - Initial release.

# ------------
# REQUIREMENTS
# ------------

#  ISOs (all available from the *HUMONGOUS CP/M* Archives):
  
#    cpmdosgg.iso                                             http://cpmarchives.classiccmp.org/downloads/cpmdosgg_iso.zip
#    sourdough_jims_cpm_archive.iso                           http://cpmarchives.classiccmp.org/downloads/sourdough_jims_cpm_archive.iso.zip
#    nicholson.iso                                            http://cpmarchives.classiccmp.org/downloads/nicholson.iso
#    November_1994_Walnut_Creek_cpm_cdrom.iso                 http://cpmarchives.classiccmp.org/downloads/November_1994_Walnut_Creek_cpm_cdrom.iso.7z
#    cpmug.iso                                                http://cpmarchives.classiccmp.org/downloads/cpmug.iso
#    oakcpm.iso                                               http://cpmarchives.classiccmp.org/downloads/oakcpm.iso.7z
  
#   Place the above ISOs together in an accessible directory and point the var $iso_loc below to it. 

#  Utilities

#   Make sure these are available somewhere in your system path.

#       imdu - Dave Dunfield's ImageDisk utility              http://dunfield.classiccmp.org/img/index.htm ; https://oldcomputers-ddns.org/public/pub/manuals/imd.pdf
#       arc  - a utility for handling CP/M .ARK archives      Debian: sudo apt install arc ; Source: https://github.com/ani6al/arc
#       crck - a utility for generating CPM-style CRC values  http://cpmarchives.classiccmp.org/cpm/mirrors/oak.oakland.edu/pub/unix-c/cpm/crck.tar.Z
#   cpmtools - specifically cpmcp                             http://www.moria.de/~michael/cpmtools/ ; https://github.com/lipro-cpm4l/cpmtools/tree/cpm4l/cpmtools-2.21
#      mklbr - create .lbr archives                           https://github.com/ogdenpm/mklbr

# -----
# USAGE
# -----

#   Place this script somewhere on your system. Read these comments for details. Download the ISO images and make sure you 
#   have all the required utilities installed (see the REQUIREMENTS section above) and available in your system path. Then 
#   edit two variables in the VARIABLES section: $iso_loc and $buildroot. You can now build a single volume; e.g.:

#     ./buildvol 228

#   Or the entire collection (on my system this takes a bit over five minutes):

#     for i in {1..310}; do ./buildvol $i; done

# ------- ----
# PROJECT GOAL
# ------- ----

# While there are several sources currently available for the SIG/M collection, none of them is "clean" or complete. Some
# sources have accreted a number of additional files (cf. Walnut Creek), have corrupted file names (ibid.), and/or have
# stripped CP/M record padding. This clean-up will focus on the following four areas:

# Complete Collection
# -------- ----------
# Individually, none of the sources has all 310 volumes; prominently, volumes 184-192 are missing from most such collections.
# By utilizing all known sources, I have been able to assemble a complete SIG/M collection, including the missing vols 184-192.

# Volume Content
# ------ -------
# Occasionally, files have gone missing from some sources. More commonly, some sources (looking at you, Walnut Creek), have
# accreted additional files. For volume content, -CATALOG and (where available) CRCKFILE are considered canonical. Only files
# listed there are included, with currently two exceptions: CRCKFILE and CRCK.COM. Both are often not listed in -CATALOG and,
# for obvious reasons CRCKFILE is not listed in CRCKFILE. Nevertheless, the presence of CRCKFILE is compelling regardless, 
# and in cases where CRCKFILE is present, it lists CRCK.COM even when -CATALOG does not. So even where CRCK.COM is not listed
# in either -CATALOG or CRCKFILE, it may be included. Exceptions are going to be Vols 1-18 where no CRCs are provided, so
# the inclusion of CRCK.COM would serve no purpose.

# File Names
# ---- -----
# File names have suffered a number of corruptions. Some characters, such as /, @ and +, which are legal under CP/M, are prob-
# lematic under other file systems, and are often found altered. / is a special problem, which has played havoc in UNIX environ-
# ments (cf. volume 195 on the Walnut Creek CD). It is stored properly as / inside the ARK, LBR and DSK images created here, but
# as _ (underscore) on the host system.

# File Dates
# ---- -----
# The CP/M file system had no capacity for storing file dates, so the original files had none. The decision has been made to
# set dates on individual files to match their volume's release date, but keep in mind that these, too, are not original dates.

# File Integrity
# ---- ---------
# CP/M had no facility for recording exact file sizes, but stored files in 128-byte records. Thus typically a file, unless it
# happened to be exactly some multiple of 128 bytes in length, was padded with a number of "garbage" bytes (commonly 1AH, since
# CP/M filled freshly formatted disks with 1AH which also doubled as an end-of-file marker for text files under CP/M) to the next
# 128-bytes. However, when the SIG/M collection passed through other OSes text files often lost this padding. Though not detri-
# mental, this resulted in CRCs which no longer match those in -CATALOG or CRCKFILE listings. This project restores the padding
# to all files that are not an exact multiple of 128 bytes in length, restoring in almost all cases original CRCs.

#----------
# VARIABLES
#----------

         low=1 ; high=310                                                                 # Define the acceptable range of vol nums
     iso_loc=/home/nathanael/mounts/saruman/web/cpmarchives/downloads                     # Where you SIG/M source ISOs are
   buildroot=/home/nathanael/mounts/saruman/web/cpmarchives/cpm/Software/UserGroups/SIGM/ # Where the rebuilt vols will be saved; 
   mkdir -p $buildroot                                                                    # each will be in a subdir called vol###/

  # Make sure user supplied a valid volume number.
  [[ -z $1          ]]                         && { echo "You must specify a volume between $low and $high; e.g., $0 52" ; exit 1; }
  [[ $1 =~ ^[0-9]+$ ]]                         || { echo "$1 is not a number. Try again."                                ; exit 1; }
  [[ "$1" -lt $low  ]] || [[ "$1" -gt $high ]] && { echo "Enter a number between $low and $high."                        ; exit 1; }
  vol=`printf %03d $1`
  builddir=$buildroot/sigmv$vol ; rm -rf $builddir > /dev/null 2>&1 ; mkdir -p $builddir
  
# ---------
# FUNCTIONS
# ---------

#    SOURCE - Mounts the source specified ("cpmdosgg", "oak", etc.) in preparation to copy the files.
# COPYFILES - Copies files from the source, uppercasing all filenames. Also corrects a few corrupted names.
# DATEFILES - Sets the file datestamps to the date of release of that volume; in most cases pulls the date from -CATALOG.
#  CHECKCRC - an attempt to automate CRC comparison, but it may be hopelessly messy. Not currently used.
#  DISMOUNT - Unmount the source mounted with SOURCE.
#    RENAME - Renames files.
#       ARK - Creates a VOL###.ARK archive file. Requires cpmtools.
#       DSK - Creates an IBM-3740-format disk image for use in CP/M emulators.
#       LBR - Creates a CP/M-style LBR archive.
#  ARCHIVES - Master routine that calls ARK, DSK and LBR.
#    REMOVE - Deletes files.                       
#       PAD - Pads file lengths with 1AH out to 128-byte multiples.
#     NOTES - Spit out some notes at the end.

# ------------
  source () { 
# ------------
  # Sources for the SIG/M collections are various ISO images from *HUMONGOUS* CP/M: nicholson.iso, cpmdosgg.iso, cpmug.iso, 
  # sourdough_jims_cpm_archive.iso, November_1994_Walnut_Creek_cpm_cdrom.iso and oakcpm.iso, placed in a single location 
  # which is specified in $iso_loc above.
  
  # The rest of this script assumes $src is pointed at the source from which the volume's content will be pulled. This 
  # function's job is to point $src at the right place depending on which collection is being used for the source. E.g., if 
  # nicholson is specified as the source and the volume is24: mount nicholson.iso to $tempdir, then point $src at 
  # $tempdir/extract/cpmug025.
  
  tempdir=$(pwd)/temp                                                # a working directory where the source iso will be mounted
  mountpoint -q $tempdir && sudo umount -l $tempdir > /dev/null 2>&1 # ensure a fresh tempdir
  [[ -d $tempdir ]] && rm -rf $tempdir              > /dev/null 2>&1
  mkdir -p $tempdir                                 > /dev/null 2>&1
  
  # You can change these if you want. $iso_loc is set in VARIABLES above.

   cpmdosgg_iso=$iso_loc/cpmdosgg.iso 
      cpmug_iso=$iso_loc/cpmug.iso 
       nich_iso=$iso_loc/nicholson.iso 
         wc_iso=$iso_loc/November_1994_Walnut_Creek_cpm_cdrom.iso
        oak_iso=$iso_loc/oakcpm.iso 
  sourdough_iso=$iso_loc/sourdough_jims_cpm_archive.iso  

  case $1 in
     cpmdosgg) # SIG/M vols 1-280 are found in CPMDOSGG dirs cpm10/, cpm11/ and cpm12/.
               mkdir -p $tempdir
               [[ -f $cpmdosgg_iso ]] && sudo mount $cpmdosgg_iso  $tempdir/ > /dev/null 2>&1 || { echo $(basename $cpmdosgg_iso) not found. ; exit 1; } 
               src=$tempdir/cpm1${vol:0:1}/1$vol/
               ;;
        cpmug) # SIG/M vols 2, 4, etc. are duplicated in CPMUG vols 56, 58, etc.
               mkdir -p $tempdir
               [[ -f $cpmug_iso ]] && sudo mount $cpmug_iso     $tempdir/ > /dev/null 2>&1 || { echo $(basename $cpmug_iso) not found. ; exit 1; }
               [[ $vol == 002 ]] && src=$tempdir/cpmug056
               [[ $vol == 004 ]] && src=$tempdir/cpmug058
               [[ $vol == 005 ]] && src=$tempdir/cpmug059
               [[ $vol == 006 ]] && src=$tempdir/cpmug060
               [[ $vol == 011 ]] && src=$tempdir/cpmug057
               [[ $vol == 015 ]] && src=$tempdir/cpmug067
               ;;
    nicholson) # nicholson is a bit complicated. A partial SIG/M set is found in .IMD format in the sigm/ directory. Also, 
               # the directory extracted/ contains subdirs holding, apparently, the extracted contents of those IMD images. 
               # I'm not sure why I did  that. Assuming the code below, using the imdu and cpmcp to extract the contents
               # works, just go with that. The way this code is currently structured, it seems to set up the extract/ source, 
               # then just switch to the IMD image anyway.
    
               mkdir -p $tempdir
               [[ -f $nich_iso ]] && sudo mount $nich_iso      $tempdir/ > /dev/null 2>&1 || { echo $basename $nich_iso not found. ; exit 1; }
               [[ -d $tempdir/extract/sigm$vol/     ]] && src=$tempdir/extract/sigm$vol/
               [[ -f $tempdir/sigm/sigm$vol.imd     ]] && { 
                 imdu -b $tempdir/sigm/sigm$vol.imd ./sigm$vol.dsk > /dev/null 2>&1
                 sudo umount -l $tempdir > /dev/null 2>&1
                 cpmcp -f ibm-3740 ./sigm$vol.dsk 0:*.* $tempdir/
                 rm -f ./sigm$vol.dsk
                 src=$tempdir
                 }
               ;;
           wc) # The Walnut Creek CD's copy of SIG/M is in simtel/sigm/ subdirs vols000/, vols100/, vols200/ and vols300/.
               mkdir -p $tempdir
               [[ -f $wc_iso ]] && sudo mount $wc_iso        $tempdir/ > /dev/null 2>&1 || { echo $wc_iso not found. ; exit 1; }
               src=$tempdir/simtel/sigm/vols${vol:0:1}00/vol$vol/
               ;;
          oak) # OAK's collection is in some ways the most complicated. While its collection is nearly complete complete 
               # (lackings vols 184-192), it is a mixture of expanded subdirs and .ARK archive files. Thus depending on the 
               # vol it can either be pulled from the expanded dir, or extracted from the .ARK archive.          
               mkdir -p $tempdir
               [[ -f $oak_iso ]] && sudo mount $oak_iso       $tempdir/ > /dev/null 2>&1 || { echo $oak_iso not found. ; exit 1; }
               [[ -d $tempdir/sigm/vol$vol/ ]] && src=$tempdir/sigm/vol$vol/ || {
                  curdir=$(pwd)
                  sudo cp $tempdir/sigm/sigmv$vol.ark $curdir/ # for some reason fails without sudo
                  sudo umount -l $tempdir > /dev/null 2>&1
                  cd $tempdir
                  arc ne $curdir/sigmv$vol.ark
                  cd $curdir/ > /dev/null 2>&1
                  rm -rf ./sigmv$vol.ark
                  curdir=
                  src=$tempdir
                  }
               ;;
    sourdough) # Sourdough's SIG/M collection is in library_collections/sigm/. Like OAK, it is a mixture of expanded
               # dirs and .ARK archives.
               mkdir -p $tempdir
               [[ -f $sourdough_iso ]] && sudo mount $sourdough_iso $tempdir/ > /dev/null 2>&1 || { echo $sourdough_iso not found. ; exit 1; }
               [[ -d $tempdir/library_collections/sigm/vol$vol/ ]] && src=$tempdir/library_collections/sigm/vol$vol || {
                  curdir=$(pwd)
                  cp $tempdir/library_collections/sigm/sigmv$vol.ark $curdir
                  sudo umount -l $tempdir > /dev/null 2>&1
                  cd $tempdir
                  arc ne $curdir/sigmv$vol.ark
                  cd $curdir/ > /dev/null 2>&1
                  rm -f $curdir/sigmv$vol.ark
                  curdir=
                  src=$tempdir
                  }
               ;;
  esac
  
  echo ""
  echo ""
  echo "============"                # Tell user where the contents are being pulled from
  echo "SIG/M VOL$vol Files from $1"
  echo "============"
  }  
  
# ------------
  copyfiles () {
# ------------
    echo ""
    echo "  Copying files"
    echo "    ----"
    echo "    From $src"
    for f in $src/* ; do cp $f $builddir/$(basename $f | tr 'a-z' 'A-Z') >/dev/null 2>&1; done  # Uppercase all filename
    for i in ./_SIGM ./-SIGM ./_SIG_M ./-SIG_M; do                              # Some collections added variants of -SIGM.xxx as volume; careful of SIG_M.$vol (see vol 2); it's legit.
    [[ -f $builddir/$i.$vol ]] && rm -rf $builddir/$i.$vol >/dev/null 2>&1      # labels. They're not original, so clean them out.
    done                                                                        

    for i in ./_CATALOG ./CATALOG; do                                           # Rename -CATALOG
      [[ -f $builddir/$i.$vol ]] && mv $builddir/$i.$vol $builddir/-CATALOG.$vol >/dev/null 2>&1
    done  

    for i in ./SIG_M.LIB ./SIG\$M.LIB ./SIG-M.LIB; do                           # Rename SIG/M.LIB
      [[ -f $builddir/$i ]] && mv $builddir/$i $builddir/SIG_M.LIB >/dev/null 2>&1
    done  

    sudo chmod 777 $builddir/*   # Some vols (e.g., 104) give "Permission denied" when the script attempts to pad the files

    echo "    ----"
  }

# ------------
  datefiles () {
# ------------              
  # SIG/M began in about Sept 1980. Early volumes (prior to vol 43) didn't include release dates.
  # Release dates used here are gleaned largely from the SIG/M newsletters on SIG/M Vol 51. In most 
  # cases only the month can be gleaned. The official day of release would presumably be that month's 
  # SIG/M meeting but those dates are unknown. Instead, the 15th of that month is arbitrarily assigned.
    case $vol in            
      001) date=19801015 ;; # The 11/80 newsletter mentions three vols already available
      002) date=19801015 ;; # and says four more would be released at that month's SIG/M 
      003) date=19801015 ;; # meeting.
      004) date=19801115 ;; 
      005) date=19801115 ;; 
      006) date=19801115 ;; 
      007) date=19801115 ;; 
      008) date=19801215 ;; # No mention of vols 8-11 in the SIG/M newsletters, so for no
      009) date=19810115 ;; # good reason, just assigning one per month until vol 12.
      010) date=19810215 ;; 
      011) date=19810315 ;; 
      012) date=19810415 ;; 
      013) date=19810415 ;; 
      014) date=19810415 ;; 
      015) date=19810415 ;; 
      016) date=19810415 ;; 
      017) date=19810515 ;; # The 5/81 newsletter mentions vols 17 and 18 as released
      018) date=19810515 ;; 
      019) date=19810615 ;; # 6/81 calls vols 12-25 "new releases"
      020) date=19810615 ;; 
      021) date=19810615 ;; 
      022) date=19810615 ;; 
      023) date=19810615 ;; 
      024) date=19810615 ;; 
      025) date=19810615 ;; 
      026) date=19810901 ;; # 8/81 says 11 vols will be released in July/Aug. Then
      027) date=19810901 ;; # 9/81 lists vols 26-38.
      028) date=19810901 ;; 
      029) date=19810901 ;; 
      030) date=19810901 ;; 
      031) date=19810901 ;; 
      032) date=19810901 ;; 
      033) date=19810901 ;; 
      034) date=19810901 ;; 
      035) date=19810901 ;; 
      036) date=19810901 ;; 
      037) date=19810901 ;; 
      038) date=19810901 ;; 
      039) date=19811015 ;; # 10/81 lists vols 39-42
      040) date=19811015 ;; 
      041) date=19811015 ;; 
      042) date=19811015 ;; 
      052) date=19820101 ;; # No release date; assuming Vol 51/53's date.
      055) date=19820205 ;; # No release date; interpolating between vols 54/56.
      059) date=19820317 ;; # -CATALOG date formatting screws up the extraction code; specifying the date manually.
      092) date=19830114 ;; # -CATALOG date formatting screws up the extraction code; specifying the date manually.
      093) date=19830115 ;; # -CATALOG date formatting screws up the extraction code; specifying the date manually.
      118) date=19830614 ;; # -CATALOG date formatting screws up the extraction code; specifying the date manually.
      128 | 129) date=19830909 ;; # -CATALOG date formatting screws up the extraction code; specifying the date manually.
      135) date=19830901 ;; # -CATALOG date formatting screws up the extraction code; specifying the date manually.
      153) date=19840206 ;; # -CATALOG date formatting screws up the extraction code; specifying the date manually.
      291 | 292 | 293 | 294) date=19861121 ;; # -CATALOG date formatting screws up the extraction code; specifying the date manually.
      295 | 296 | 297 | 298 | 299) date=19870815 ;; # No release date. Assuming it goes with vol 296.
      300 | 301) date=19870915 ;; # Release dates for vols 296-310 are MM/YY only. The 15th of those months is arbitrarily assigned.
      302 | 303) date=19871115 ;; 
      304 | 305 | 306 | 307 | 308 | 309 | 310) date=19880315 ;; 
        *) date=$(grep released $builddir/-CATALOG.$vol | rev | cut -d' ' -f1-3 | rev) ;;
    esac      
    echo ""
    echo "  VOLDATE"
    echo "    ----"
    echo "    $date"
    echo "    ----"
    touch -d "$date" $builddir/*
    touch -d "$date" $builddir
  } 
  
# ------------
  checkcrc () {
# ------------

    # Verify file integrity by comparing the file's actual CRC with the CRC listed in -$crcfile. Here's a sample -CATALOG file listing, for ADDADR.ASM:
    #    49.01   ADDADR  .ASM     1K     3B 9E   Accounts Payable/Receivable

    # So 1) get the file's actual CRC with cpmcrck. 2) grep the file listing in -CATALOG and extract the CRC value (3B 9E above) from it. 3) Compare.
    
    cd $builddir >/dev/null 2>&1
    echo ""
    echo "  File Integrity"
    echo "    ----"
    
    # A combination of $fields and $bytes is used to extract the file's listed CRC value from $crcfile. $crcfile is one of CRCKFILE.$vol, CRCKLIST.$vol or -CATALOG.$vol.
    
    crcfile="./-CATALOG.$vol" ; fields="-f3" ; bytes="-b13-17" # defaults

    # For most volumes, the above defaults work. Put exceptions here. Note $((10#$vol))) converts to base 10
    # which strips the leading zero (e.g., 049 --> 49), which would cause BASH to interpret it as a hex value.
    # Note: this is for volume-wide settings. Any individual file within a volume that needs special attention
    # is handled below.
    
    [[ $(echo $((10#$vol))) -le  18 ]]                                       && { echo "    No CRCs available"  ; echo "    ----" ; return      ; } # Vols 1-18 no CRCs
    [[ $(echo $((10#$vol))) -le  25 ]]                                       && { crcfile="./CRCKFILE.$vol" ; fields="-f2"    ; bytes="-b12-16" ; } # Vols 19-25
    [[ $(echo $((10#$vol))) -ge  26 ]] && [[ $(echo $((10#$vol))) -le  48 ]] && { crcfile="./CRCKLIST.$vol" ; fields="-f2"    ; bytes="-b12-16" ; } # Vols 26-48
    [[ $(echo $((10#$vol))) -ge  49 ]] && [[ $(echo $((10#$vol))) -le  50 ]] && {                                               bytes="-b9-13"  ; } # Vols 49-50
    [[ $(echo $((10#$vol))) -eq  51 ]] &&                                       {                                               bytes="-b5-9"   ; } # Vol  51
    [[ $(echo $((10#$vol))) -ge  52 ]] && [[ $(echo $((10#$vol))) -le  75 ]] && {                                               bytes="-b9-13"  ; } # Vols 52-75
    [[ $(echo $((10#$vol))) -eq  76 ]] || [[ $(echo $((10#$vol))) -eq  78 ]] && {                                               bytes="-b11-15" ; } # Vols 76, 78
    [[ $(echo $((10#$vol))) -ge  83 ]] && [[ $(echo $((10#$vol))) -le  84 ]] && {                                               bytes="-b11-15" ; } # Vols 83, 84
    [[ $(echo $((10#$vol))) -ge  86 ]] && [[ $(echo $((10#$vol))) -le  93 ]] && {                                               bytes="-b11-15" ; } # Vols 86-93
    [[ $(echo $((10#$vol))) -ge  94 ]] && [[ $(echo $((10#$vol))) -le 114 ]] && {                                               bytes="-b12-16" ; } # Vols 94-114

    # Cycle through the files in the current volume.
    
    for i in ./*; do

      actualcrc="$(cpmcrck $i | tail -1 | cut -b46-50 | tr 'a-z' 'A-Z')"            # get the file's actual CRC

      # break out name and extension portions of filename, and build $expandedname.
      
      f=$(basename $i) 
      name=$(echo $f | cut -d'.' -f1)                                               # strip './' and grab filename portion without extension
      ext=$( echo $f | cut -d'.' -f2); [[ $ext == $name ]] && ext="   "             # grab filename ext only; set to '   ' if none
      expandedname="$(printf "%-8.15s.%s" $name $ext)"                              # Pad out to full 8.3; e.g., "CRC.COM" to 'CRC     .COM'

      [[ ! "$ext" == "$vol" ]] && [[ ! "${f:0:1}" == "-" ]] && { # Skip any file whose extension is the vol number (-CATALOG.049) or whose name starts with -.

        # If an individual file is an exception to the volume-wide $fields and/or $bytes settings, put it here.
      
        orgbytes=$bytes                                                             # Save current value for later restoration

        case $f in
           "ARCUSTM.DCL" )                  bytes="-b10-14" ;;                      # Vol 49
          "CHGLIB22.LBR" )                  bytes="-b10-14" ;;                      # Vol 250
          "PRAELUD1.SNG" | "SCARLATI.SNG" ) bytes="-b10-14" ;;                      # Vol 57
            "FLS-11.COM" )                  bytes="-b16-20" ;;                      # Vol 60
                  "NEWS" )                  bytes="-b11-15" ;;                      # Vol 249
              "SYOPMENU" )                  bytes="-b10-14" ;;                      # Vol 249
        esac
          
        # Define the name to grep for in $crcfile. Can add exceptions for individual files.
        
        case $expandedname in 
          "CRC     .COM" ) [[ $(echo $((10#$vol))) -eq 89  ]] || [[ $(echo $((10#$vol))) -eq 108 ]] && grepname="CRC    .COM" ;;  # Vol 89  CRC.COM is improperly listed as "CRC    .COM" (only three spaces)
          "GLOBALS .RN$" ) grepname="GLOBALS .RN" ;; # Vol 134
          "HELP    .COM" ) [[ $(echo $((10#$vol))) -eq 89  ]] && grepname="HELP   .COM" ;; # Vol 89 HELP.COM is improperly listed as "HELP   .COM" (only three spaces)
          "JOIN    .ACG" ) [[ $(echo $((10#$vol))) -eq 89  ]] && grepname="JOIN.ACG"    ;; # Vol 146
          "PASZCODE.RN$" ) grepname="PASZCODE.RN" ;; # Vol 134
          "MDBSGETM.PLI" ) grepname="MDBSGETM.PL"                                       ;; # Vol 49
          "PRICES  .DOC" ) grepname="PRICES.DOC"                                        ;; # Vol 53
          "SIG_M   .LIB" ) [[ $(echo $((10#$vol))) -eq 146 ]] && grepname="SIG/M.LIB" || grepname="SIG/M   .LIB" # Vol 146
                           [[ $(echo $((10#$vol))) -ge 193 ]] && grepname="SIG-M   .LIB"   # Vols 193-310
                           ;;
          "TESTPROT.BAS" ) grepname="TestProt.BAS" ;; # Vol 52
          "Z2SYS-1 .MOD" ) grepname="Z2SYS-1.MOD"                                       ;; # Vol 108
                        *) grepname=$(echo "$expandedname" | tr '_' '/')                ;; # Replace _ with / before grepping.
        esac
  
        # Search for $grepname in $crcfile. Report if not found. If found, extract the CRC.

        grep -i "$grepname" $crcfile >/dev/null || echo "    $expandedname not listed in $crcfile" # VOL $vol >> ~/projects/sigm/notlisted
        grep -i "$grepname" $crcfile >/dev/null && { 
          case $f in
            # Some files are listed, but without CRCs, so CRCs are manually supplied here. Some have undergone revisions and require multiple CRCs.
            # To check all the CRCs of a file, go to $buildroot and run:
            #    fn=CRC.COM; for i in {001..310}; do   [[ -f sigmv$i/$fn ]] && cpmcrck sigmv$i/$fn | tail -1; done
            "CRC.CMD"      ) expectedcrc=10E5 ;;                                                          
            "CRC.COM"      )                                       expectedcrc=B207
                             [[ $(echo $((10#$vol))) -eq 102 ]] && expectedcrc=BB23
                             [[ $(echo $((10#$vol))) -ge 216 ]] && expectedcrc=EE87
                             [[ $(echo $((10#$vol))) -ge 295 ]] && expectedcrc=CB3E
                             [[ $(echo $((10#$vol))) -eq 296 ]] && expectedcrc=053B
                             [[ $(echo $((10#$vol))) -eq 299 ]] && expectedcrc=EE87
                             [[ $(echo $((10#$vol))) -ge 300 ]] && expectedcrc=B207
                             ;;                 
            "CRCK.COM"     ) expectedcrc=2D47 ;;
            "DELBR.COM"    ) expectedcrc=EF3A ;; 
            "HELP.COM"     ) expectedcrc=D6CC ; [[ $(echo $((10#$vol))) -eq 102 ]] && expectedcrc=3447 ; [[ $(echo $((10#$vol))) -ge 186 ]] && expectedcrc=928B ;;
            "JOIN.ACG"     ) expectedcrc=83E7 ; [[ $(echo $((10#$vol))) -ge 153 ]] && expectedcrc=9B11 ; [[ $(echo $((10#$vol))) -ge 174 ]] && expectedcrc=83E7 ; [[ $(echo $((10#$vol))) -ge 282 ]] && expectedcrc=A289 ; [[ $(echo $((10#$vol))) -ge 295 ]] && expectedcrc=83E7 ;;
            "JOIN.AZG"     ) expectedcrc=3EC0 ; [[ $(echo $((10#$vol))) -ge 305 ]] && expectedcrc=3E32 ;;
            "LTYPE.COM"    ) expectedcrc=AC16 ;;                                                          
            "LU.COM"       ) expectedcrc=3D98 ; [[ $(echo $((10#$vol))) -ge 157 ]] && expectedcrc=BA32 ;; 
            "LU86.CMD"     ) expectedcrc=1723 ;;   
            "MDBSGETM.PLI" ) expectedcrc=B7A1 ;; # Vol 49
            "PRICES.DOC"   ) expectedcrc=6CC7 ;; # Vol 53
            "READTHIS"     )                                       expectedcrc=2AE0 # Vols 164-166
                             [[ $(echo $((10#$vol))) -eq 173 ]] && expectedcrc=BB80 
                             [[ $(echo $((10#$vol))) -eq 197 ]] && expectedcrc=58FF
                             ;;                 
            "READ.ME"      ) [[ $(echo $((10#$vol))) -eq 184 ]] && expectedcrc=D9F5 ;; # Vol 184
            "READTHIS.1ST" ) expectedcrc=CCAE ;; # Vol 168
            "REGIONS.SIG"  ) expectedcrc=3214 ; [[ $(echo $((10#$vol))) -ge 252 ]] && expectedcrc=FD05 ;;
            "SHOW.COM"     ) expectedcrc=F628 ;; 
            "SIG_M.LIB"    )                                       expectedcrc=C9BE
                             [[ $(echo $((10#$vol))) -eq 104 ]] && expectedcrc=93AE
                             [[ $(echo $((10#$vol))) -ge 118 ]] && expectedcrc=1539
                             [[ $(echo $((10#$vol))) -ge 200 ]] && expectedcrc=D31C
                             [[ $(echo $((10#$vol))) -ge 208 ]] && expectedcrc=15CA
                             [[ $(echo $((10#$vol))) -eq 243 ]] && expectedcrc=0C6F
                             [[ $(echo $((10#$vol))) -eq 253 ]] && expectedcrc=0C6F
                             [[ $(echo $((10#$vol))) -ge 278 ]] && expectedcrc=0C6F
                             [[ $(echo $((10#$vol))) -ge 291 ]] && expectedcrc=F4DD
                             [[ $(echo $((10#$vol))) -ge 295 ]] && expectedcrc=15CA
                             ;;                 
            "SIG/M.LIB"    ) expectedcrc=C9BE ;;                                                          
            "SIG-M.LZB"    ) expectedcrc=F286 ;;                                                          
            "TYPE1.COM"    ) expectedcrc=56FB ; [[ $(echo $((10#$vol))) -ge 184 ]] && expectedcrc=FFD7 ;; 
            "USQ.COM"      ) expectedcrc=561F ; [[ $(echo $((10#$vol))) -ge 152 ]] && expectedcrc=5621 ; [[ $(echo $((10#$vol))) -ge 176 ]] && expectedcrc=7D52 ;;
            "USQ.CMD"      ) expectedcrc=24C0 ; [[ $(echo $((10#$vol))) -ge 175 ]] && expectedcrc=F46E ; [[ $(echo $((10#$vol))) -ge 207 ]] && expectedcrc=24C0 ; [[ $(echo $((10#$vol))) -ge 210 ]] && expectedcrc=EB7C ; [[ $(echo $((10#$vol))) -ge 229 ]] && expectedcrc=0CAF ;;
            "Z2SYS-1.MOD"  ) expectedcrc=3DF1 ;; # Vol 108
            "ZCPR2.IDX"    ) expectedcrc=63C6 ; [[ $(echo $((10#$vol))) -ge 124 ]] && expectedcrc=0BA7 ;;
            "ZCPR3.CAT"    ) expectedcrc=95F2 ;;
                          *) expectedcrc=$(grep -a "$grepname" $crcfile | cut -d'.' $fields | cut $bytes | tr -d [:space:] | cut -b1-4) ;;
          esac                 
          
          # Finally, if the actual and listed CRCs don't match, report it.
          
          [[ ! "$actualcrc" == "$expectedcrc" ]] && echo "    $expandedname CRC mismatch **** ACTUAL: $actualcrc EXPECTED: $expectedcrc" # VOL $vol >> ~/projects/sigm/mismatches
        }

       bytes=$orgbytes # restore original value in case it was altered, so the rest of the files in this volume aren't processed with the wrong value.
       }  
    done

    echo "    ----"
    #read -p "Continue..."
    cd - >/dev/null 2>&1
  }
  
# ------------
  dismount () {
# ------------
    mountpoint -q $tempdir > /dev/null 2>&1 && sudo umount -l $tempdir > /dev/null 2>&1
    rm -rf $tempdir > /dev/null 2>&1
  }
  
# ------------
  rename () {
# ------------
    # To rename single files (each pair wrapped in quotations):
    #   rename './oldname ./newname' './oldname ./newname'
    
    # To batch rename a wildcarded spec:
    #   rename 'DU_*.*'

    # NOTE: Use the wildcarded option only when you wish to
    # replace _ with -. If you wish to replace _ with some
    # other char, use single file format.
    
    cd $builddir >/dev/null 2>&1 
    echo ""
    echo "  Rename"
    echo "    ----"
    for i in "$@"; do 
      echo "$i" | grep "*" > /dev/null && { 
        for j in $i; do
          echo "    $j $(echo $j | tr '_' '-')"
          mv $j $(echo $j | tr '_' '-')
          done
        } || { echo "    $i"; mv $i; }
    done
    [[ -f "SIG-M.LIB" ]] && mv SIG-M.LIB SIG_M.LIB # In case SIG_M.LIB got caught up in any wildcard sweeps, name it back
    echo "    ----"
    cd - >/dev/null 2>&1 
#    echo "    $1  to $2"
#    mv $builddir/$1  $builddir/$2
  }
  
# ------------
  ark () {
# ------------
    which arc    &> /dev/null 1>&2 || { echo "arc util not found"     ; return; }
    dest=$buildroot/ARK; arkname=$dest/SIGMV$vol.ARK
    cd                   $builddir                  &> /dev/null 1>&2
    mkdir -p             $dest                      &> /dev/null 1>&2
    [[ -f                $arkname ]] && rm $arkname &> /dev/null 1>&2  # remove any previous version

    # build archive
    arc a                $arkname ./*               &> /dev/null 1>&2

    # On my Linux system I'm using arc v5.21r, which translates between / and :. But on the host system, I've replaced / with _, which arc 
    # doesn't pick up, so here I'll manually convert _ to / inside the ARK files. Note that arc will translation / to : when listing or
    # extracting the ARK contents, but internally it is stored as /.

    for j in ./*; do {
      oldname=$(echo $(basename $j) | cut -d'.' -f1)                              # filename with _
      newname=$(echo $oldname | tr '_' '/')                                       # filename with /
      [[ ! "$oldname" == "$newname" ]] && sed -i "s|$oldname|$newname|g" $arkname # could also do something like echo $newname | grep "/"
      }
    done
    
    touch -r .           $arkname                   &> /dev/null 1>&2  # set datestamp of ARK
    touch -d "19880315"  $dest                                         # set datestamp of ARK dir to date of most recent SIG/M volume (i.e., vol 310)
    
    # clean up
    cd -                                            &> /dev/null 1>&2
    echo "    $(basename $arkname)"
  }
  
# ------------
  dsk () {
# ------------
    which mkfs.cpm &> /dev/null 1>&2 || { echo "mkfs.cpm util not found"; return; }
    which cpmcp    &> /dev/null 1>&2 || { echo "cpmcp util not found"   ; return; }
    dest=$buildroot/DSK; dskname=$dest/SIGMV$vol.DSK
    cd                   $builddir                  &> /dev/null 1>&2
    mkdir -p             $dest                      &> /dev/null 1>&2
    [[ -f                $dskname ]] && rm $dskname &> /dev/null 1>&2  # remove any previous version

    # build archive
    mkfs.cpm -f ibm-3740 $dskname                   &> /dev/null 1>&2
    cpmcp -f    ibm-3740 $dskname ./* 0:            &> /dev/null 1>&2
    touch -r .           $dskname                   &> /dev/null 1>&2  # set datestamp of DSK
    touch -d "19880315"  $dest                                         # set datestamp of DSK dir to date of most recent SIG/M volume
    
    # clean up
    cd -                                            &> /dev/null 1>&2
    echo "    $(basename $dskname)"
  }

# ------------
  lbr () {
# ------------
    which mklbr &> /dev/null 1>&2   || { echo "mklbr util not found"   ; return; }
    dest=$buildroot/LBR; lbrname=$dest/SIGMV$vol.LBR ; recipe=$dest/$vol.rcp
    cd                   $builddir                  &> /dev/null 1>&2
    mkdir -p             $dest                      &> /dev/null 1>&2
    [[ -f                $lbrname ]] && rm $lbrname &> /dev/null 1>&2  # remove any previous version

    # build archive
    echo                "$lbrname"       > $recipe
    for j in *; do echo "$builddir/$j?$(echo $j | tr '_' '/')"  >> $recipe; done
    mklbr                $recipe
    rm                   $recipe
    
    # The version of mklbr I'm using doesn't translate _ to / when creating the LBR. So do it manually.
    # UPDATE: Turns out mklbr can do the translation; I've updated to code above and this is now obsolete.

#    for j in ./*; do {
#      oldname=$(echo $(basename $j) | cut -d'.' -f1)                              # filename with _
#      newname=$(echo $oldname | tr '_' '/')                                       # filename with /
#      [[ ! "$oldname" == "$newname" ]] && sed -i "s|$oldname|$newname|g" $lbrname # could also do something like echo $newname | grep "/"
#      }
#    done

    touch -r .           $lbrname                   &> /dev/null 1>&2  # set datestamp of LBR
    touch -d "19880315"  $dest                                         # set datestamp of LBR dir to date of most recent SIG/M volume (i.e., vol 310)

    # clean up
    cd -                                            &> /dev/null 1>&2
    echo "    $(basename $lbrname)"
  }
  
# ------------
  archives () {
# ------------
    echo ""
    echo "  Archives"
    echo "    ----"
    ark; dsk; lbr 
    echo "    ----"
  }

# ------------
  remove () {
# ------------
    echo ""
    echo "  Remove"
    echo "    ----"
    for i in $1; do
      echo "    $i"
      rm $builddir/$i > /dev/null 1>&2
    done
    echo "    ----"
  }
  
# ------------
  pad () {
# ------------

  # Under CP/M all files were stored in 128-byte records, such that files which were not a multiple of 128 bytes
  # in length were padded with garbage to the next 128-byte boundary (If the files were originally copied to 
  # fresh disks, the padding consisted of 1AH bytes). Over many years of passing through various file systems, 
  # many of the text files in the SIG/M collection have lost that additional padding, resulting in files which no
  # match the original CRC values. This routine will pad any file whose length is not an exact multiple of 128 to 
  # the next 128-byte multiple with 1AH. This fixes most CRC mismatches.

    sudo chmod 777 $builddir/*   # Some vols (e.g., 104) give "Permission denied"

    echo ""
    echo "  Padding"
    echo "    ----"

    for f in $builddir/*; do
      count=$((128-$(($(ls -l $f | cut -d' ' -f5)%128)))) # number of bytes needed to next 128
      [[ $count -eq 128 ]] && count=0 || echo "    $(basename $f) with $count bytes" # Reset to 0 to avoid padding files that are already a multiple of 128 bytes
 
      for (( c=1; c<=$count; c++)); do 
        printf "%b" '\x1A' >> $f
      done  
    done  

    echo "    ----"

  }
  
# ------------
  notes () {
# ------------
    echo ""
    echo "  Notes"
    echo "    ----"
    for i in "$@"; do echo "    $i"; done
    echo "    ----"
  }

#-----
# MAIN
#-----

# All volumes' CRCs and filenames have been manually compared to crckfile/crcklist/-catalog.

  case $vol in # Build the specified volume.
  
    # General process: mount the source, copy the files, dismount the source, pad the files, set datestamps, build ARK/LBR/DSK archives, and finally show the file CRCs.
    # Reminder (cuz I'm always in danger of forgetting why): datefiles must run before archives so that files have proper dates before they're archived. 
  
    001) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    002) source cpmug    ; copyfiles; dismount; pad;                    rename "./SIG_M.$vol ./-CATALOG.$vol"                            ; datefiles; archives; checkcrc ;;
    003) source oak      ; copyfiles; dismount; source wc ; head -n 15 $src/../vol015/sigmlog.003 > $builddir/-CATALOG.$vol; tail -n 12 $src/../vol015/sigmlog.003 > $builddir/ABSTRACT.$vol; dismount; pad; datefiles; archives; checkcrc ;;
    004) source cpmug    ; copyfiles; dismount; pad; remove SIG_M.LIB;  rename "DU_8_12.ASM DU-8_12.ASM" "BDOS_PAT.ASM BDOS-PAT.ASM"     ; datefiles; archives; checkcrc ;;
    005) source cpmug    ; copyfiles; dismount; pad; remove SIG_M.LIB;  rename "CP_M_NET.MSG CP_M-NET.MSG"                               ; datefiles; archives; checkcrc ;;
    006) source cpmug    ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    007) source nicholson; copyfiles; dismount; pad; remove SIG_M.LIB                                                                    ; datefiles; archives; checkcrc ;;
    008) source cpmdosgg ; copyfiles; dismount; pad; remove SIG_M.LIB                                                                    ; datefiles; archives; checkcrc ;;
    009) source nicholson; copyfiles; dismount; pad; remove SIG_M.LIB                                                                    ; datefiles; archives; checkcrc ;;
    010) source nicholson; copyfiles; dismount; pad; remove SIG_M.LIB                                                                    ; datefiles; archives; checkcrc ;;
    011) source cpmug    ; copyfiles; dismount; pad; remove SIG_M.LIB                                                                    ; datefiles; archives; checkcrc ;;
    012) source cpmdosgg ; copyfiles; dismount; pad; remove SIG_M.LIB                                                                    ; datefiles; archives; checkcrc ;;
    013) source nicholson; copyfiles; dismount; pad; remove SIG_M.LIB                                                                    ; datefiles; archives; checkcrc ;;
    014) source cpmdosgg ; copyfiles; dismount; pad; remove SIG_M.LIB                                                                    ; datefiles; archives; checkcrc ;;
    015) source cpmug    ; copyfiles; dismount; pad;                    rename "./-CATALOG.015  CATALOG.015" "DCATALOG.015 ./-CATALOG.015";datefiles; archives; checkcrc ;;
    016) source cpmdosgg ; copyfiles; dismount; pad; remove SIG_M.LIB;  rename "DU_*" "FILE_*"                                           ; datefiles; archives; checkcrc ;;
    017) source cpmdosgg ; copyfiles; dismount; pad; remove SIG_M.LIB;  rename "SORTV_*" "./_CATALOG.ACK ./-CATALOG.ACK"                 ; datefiles; archives; checkcrc ;;
    018) source nicholson; copyfiles; dismount; pad; remove SIG_M.LIB;  rename "CATALOG.ACK  ./-CATALOG.ACK"                             ; datefiles; archives; checkcrc ;;
    019) source nicholson; copyfiles; dismount; pad;                    rename "CATALOG.ACK ./-CATALOG.ACK";                               datefiles; archives; checkcrc ;; # CRCK.COM, SIG/M.LIB: in CRCKFILE.019 and on disk but not -CATALOG.019. CRCKFILE.019: in -CATALOG.019 and on disk but not in CRCKFILE.019
    020) source nicholson; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;; # -CATALOG.020 CRC mismatch; CRCK.COM not listed in -CATALOG; CRCKFILE.020 not listed in CRCKFILE.
    021) source sourdough; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    022) source sourdough; copyfiles; dismount; pad; remove SIG_M.LIB                                                                    ; datefiles; archives; checkcrc ;; # LESSON4 in CRCKFILE, not in -CATALOG. TEST.DAT in CRCKFILE, not in -CATALOG.
    023) source nicholson; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;; # SIG_M.LIB in CRCKFILE, not in -CATALOG. CRCK.COM in CRCKFILE, not in -CATALOG. CRCKFILE in -CATALOG, not in CRCKFILE.
    024) source nicholson; copyfiles; dismount; pad;                    rename "CATALOG.ACK ./-CATALOG.ACK"                              ; datefiles; archives; checkcrc ;;
    025) source nicholson; copyfiles; dismount; pad;                    rename "CATALOG.ACK ./-CATALOG.ACK"                              ; datefiles; archives; checkcrc ;;
    026) source cpmdosgg ; copyfiles; dismount; pad;           rename "EL_*" "./_CATA026.ACK ./-CATA026.ACK" "NAME-ADD.DOC NAME&ADD.DOC" ; datefiles; archives; checkcrc ;;
    027) source cpmdosgg ; copyfiles; dismount; pad;                    rename "./_CATA027.ACK ./-CATA027.ACK"                           ; datefiles; archives; checkcrc ;;
    028) source cpmdosgg ; copyfiles; dismount; pad;                    rename "LIFE_*" "NAME_*" "_CATA028.ACK ./-CATA028.ACK" "NAME-ADD.DOC NAME&ADD.DOC" ; datefiles; archives; checkcrc ;;
    029) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    030) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    031) source nicholson; copyfiles; dismount; pad;                    rename "CATA031.ACK ./-CATA031.ACK"                              ; datefiles; archives; checkcrc  ; notes "Only Nicholson yields fully matching CRCs." ;;
    032) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    033) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    034) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    035) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    036) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    037) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    038) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    039) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc  ; notes "-CATALOG.039 CRC mismatch" ;;
    040) source cpmdosgg ; copyfiles; dismount; pad;                    rename " MENU_*" "RUN80_*" "VMAP_*"                              ; datefiles; archives; checkcrc ;;
    041) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    042) source cpmdosgg ; copyfiles; dismount; pad;                    rename "HD_*"                                                    ; datefiles; archives; checkcrc ;;
    043) source oak      ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    044) source cpmdosgg ; copyfiles; dismount; pad;                    rename "DU_*" "SD_*"  "WASH_*"                                   ; datefiles; archives; checkcrc  ; notes "-CATALOG.044 lists WASH-16.ASM; however, all known extanct" "SIG/M collections have WASH-14.ASM." ;;
    045) source cpmdosgg ; copyfiles; dismount; pad; remove READ.ME                                                                      ; datefiles; archives; checkcrc ;; # README isn't in any file list, and is just a portion of DUNGEO.DOC in any case. Bye-bye.
    046) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    047) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    048) source cpmdosgg ; copyfiles; dismount; pad;                    rename "CRCKLIST.043 CRCKLIST.048"                               ; datefiles; archives; checkcrc ;;
    049) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc  ; notes "Corruption in -CATALOG.049 makes it impossible to" "extract MDBSGETM.PLI's CRC." ;;
    050) source cpmdosgg ; copyfiles; dismount; pad                             ; rename "TALK_.LIB TALK@.LIB" "VOIC_.DOC VOIC@.DOC" "VOIC_.LIB VOIC@.LIB" "VOIC_EQU.LIB VOIC@EQU.LIB"; datefiles; archives; checkcrc ;; # _ replaces @ instead of /; need to account for this
    051) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;; 
    052) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;; 
    053) source cpmdosgg ; copyfiles; dismount; pad;                              rename "X_UTIL.SAM X\$UTIL.SAM" "READ_ME.DOC READ-ME.DOC"  ; datefiles; archives; checkcrc ;; 
    054) source cpmdosgg ; copyfiles; dismount; pad;                              rename "I_O_CAP.ADD I_O-CAP.ADD" "I_O_CAP.ASM I_O-CAP.ASM" ; datefiles; archives; checkcrc ;; 
    055) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;; 
    056) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;; 
    057) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;; 
    058) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;; 
    059) source oak      ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc  ; notes "Unfortunately, none of the extant sources" "yields matching CRCs." ;;     
    060) source cpmdosgg ; copyfiles; dismount; source oak ; cp $tempdir/SIG-M.LIB $builddir/; dismount; pad; remove "CRCK.COM SIG_M.LIB"; rename "*_*" "SQ-USQ15.DOC SQ_USQ15.DOC" ; datefiles; archives; checkcrc;   notes "Only cpmdosgg's RBBS22.DOC and RBSUTL22.ASC" "match CRCs. However it lacks SIG/M.LIB, which" "is pulled from OAK." ;;
    061) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    062) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    063) source cpmdosgg ; copyfiles; dismount; pad;                    rename "NAD_*"                                                   ; datefiles; archives; checkcrc ;;
    064) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    065) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    066) source cpmdosgg ; copyfiles; dismount; pad; sed -i 's:CMMMAND:COMMAND:g' $builddir/ZCPR_14.ASM; rename "ZCPR*" "SD_*"           ; datefiles; archives; checkcrc ;; # At some point after CRCs were generated, a single byte in ZCPR_14.ASM was altered. Changing it back restores the proper CRC.
    067) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    068) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    069) source cpmdosgg ; copyfiles; dismount; pad;                    rename "CUB__.DAT CUB++.DAT"                                     ; datefiles; archives; checkcrc ;;
    070) source cpmdosgg ; copyfiles; dismount; pad;                    rename "A_*" "STARTRE_.NBP STARTRE\$.NBP"                        ; datefiles; archives; checkcrc ;;
    071) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    072) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    073) source cpmdosgg ; copyfiles; dismount; pad;                    rename "COMP_*" "PAGE_*" "VD*"                                   ; datefiles; archives; checkcrc ;;
    074) source cpmdosgg ; copyfiles; dismount; pad;                    rename "CLOCK_*"                                                 ; datefiles; archives; checkcrc ;;
    075) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    076) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    077) source cpmdosgg ; copyfiles; dismount; pad;                    rename "*CPR_*"                                                  ; datefiles; archives; checkcrc ;;
    078) source cpmdosgg ; copyfiles; dismount; pad;                    rename "*TALK1_*"                                                ; datefiles; archives; checkcrc ;;
    079) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    080) source oak      ; copyfiles; dismount; pad; for j in "ARTIL" "SAMPLE"; do for i in $builddir/$j-*; do mv $i $(echo $i | tr '-' '_'); done; done; datefiles; archives; checkcrc  ; notes "Unfortunately, none of the extant sources" "yields matching CRCs." ;;
    081) source oak      ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    082) source oak      ; copyfiles; dismount; pad;                    rename "ABSTRACT.081 ABSTRACT.082"                               ; datefiles; archives; checkcrc ;;
    083) source cpmdosgg ; copyfiles; dismount; pad;                    rename "ICE_*.*"                                                 ; datefiles; archives; checkcrc ;;
    084) source oak      ; copyfiles; dismount; source cpmdosgg ; cp $src/entrbbs.bas $builddir/ENTRBBS.BAS; dismount; pad; rename "FINDP.ASM FIND+.ASM" "FINDP.COM FIND+.COM" "XSTAMP.ASM XSTAM+.ASM" "XSTAMP.COM XSTAM+.COM" "CRC CRC.COM"   ; datefiles; archives; checkcrc ;;
    085) source cpmdosgg ; copyfiles; dismount; source oak; cp $src/SIGNS.COM  $builddir/SIGNS.COM; cp -f $src/RUNOFF.COM $builddir/RUNOFF.COM; cp -f $src/PASDIR.PAS $builddir/PASDIR.PAS; cp -f $src/REMOVECC.PAS $builddir/REMOVECC.PAS; cp -f $src/TRIMCOLS.PAS $builddir/TRIMCOLS.PAS; cp -f $src/XSUB.COM $builddir/XSUB.COM; dismount; pad; datefiles; archives; checkcrc  ; notes "Must mix and match CPMDOSGG and OAK" "to complete a set of intact files." ;;
    086) source oak      ; copyfiles; dismount; pad; remove "U.COM";    rename "FAST2.COM _.COM"                                         ; datefiles; archives; checkcrc  ; notes "Both CPMDOSGG and OAK have U.COM" "which is not listed in -CATALOG." "It is retained for now." ;;
    087) source cpmdosgg ; copyfiles; dismount; source oak; cp $src/BDSCAT.AQL $builddir/; cp $src/RATFOR.HLP $builddir/; dismount; rename "DISPLAY_.ASM DISPLAY+.ASM" "DISPLAY_.COM DISPLAY+.COM" "TYP_.ASM TYP+.ASM" "TYP_.COM TYP+.COM" "THIS_*"; datefiles; archives; checkcrc ;;
    088) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    089) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc  ;  notes "SYSLIBI.WS is on disk but not listed in -CATALOG." ;;
    090) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    091) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc  ;  notes "READ.ME is on disk but not listed in -CATALOG." ;;
    092) source cpmdosgg ; copyfiles; dismount; pad; rename "LITL_ADA.ASM LITL-ADA.ASM" "LITL_ADA.DOC LITL-ADA.DOC" "LITL_ADA.PRN LITL-ADA.PRN" "RBBS_USE.DOC RBBS-USE.DOC" ; datefiles; archives; checkcrc ;;
    093) source cpmdosgg ; copyfiles; dismount; source oak; cp $src/trsmodem.com $builddir/TRSMODEM.COM; dismount; pad                   ; datefiles; archives; checkcrc ;;
    094) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    095) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    096) source cpmdosgg ; copyfiles; dismount; pad; rename "CRCK_51.A86 CRCK-51.A86" "FILE_EXT.A86 FILE-EXT.A86" "XDIR_A86.DOC XDIR-A86.DOC" ; datefiles; archives; checkcrc ;;
    097) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    098) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    099) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    100) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    101) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    102) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    103) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    104) source oak      ; copyfiles; cp $tempdir/sigm/vol104/sig/m.lib $builddir/SIG_M.LIB; dismount; pad                               ; datefiles; archives; checkcrc ;;
    105) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    106) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    107) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    108) source cpmdosgg ; copyfiles; cp $tempdir/cpm11/1107/crc.com $builddir/CRC.COM ; dismount; pad; rename "Z2SYS_1.MOD Z2SYS-1.MOD" ; datefiles; archives; checkcrc ;;
    109) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc  ; notes "USERMAN1,3,4,5 are listed, but not USERMAN2.TXT" ;;
    110) source cpmdosgg ; copyfiles; dismount; pad;                    rename "*_*"                                                     ; datefiles; archives; checkcrc  ; notes "SIGN_ON.ACG, TWO_REC.FMT not in -CATALOG." ;;
    111) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    112) source cpmdosgg ; copyfiles; dismount; pad;                    rename "*_*" "RBBS-I-O.NQW RBBS-I_O.NQW"                         ; datefiles; archives; checkcrc ;;
    113) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    114) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    115) source cpmdosgg ; copyfiles; dismount; pad;                    rename "*_*"                                                     ; datefiles; archives; checkcrc ;;
    116) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    117) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc  ; notes "USQ.COM not listed in -CATALOG." ;;
    118) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    119) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    120) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    121) source cpmdosgg ; copyfiles; dismount; pad;                    rename "MDM709C_.AQM MDM709C+.AQM" "SD_*.*"                      ; datefiles; archives; checkcrc ;;
    122) source cpmdosgg ; copyfiles; dismount; pad;                    rename "DU2_*" "./ZCPR2.IDX ./-ZCPR2.IDX"                        ; datefiles; archives; checkcrc ;;
    123) source cpmdosgg ; copyfiles; dismount; pad;                    rename "FIND_*"                                                  ; datefiles; archives; checkcrc ;;
    124) source cpmdosgg ; copyfiles; dismount; pad;                    rename "ZCPR2_*"                                                 ; datefiles; archives; checkcrc ;;
    125) source cpmdosgg ; copyfiles; dismount; pad; remove __SIG_M.125;rename "ZCPR2_*"                                                 ; datefiles; archives; checkcrc ;;
    126) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    127) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    128) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    129) source oak      ; copyfiles; cp $src/db2sig/m.lbr $builddir/DB2SIG_M.LBR; dismount; pad; remove CRCKLIST.CRC                    ; datefiles; archives; checkcrc  ; notes "CPMDOSGG seems an earlier version of SIG/M. -CATALOG" "lists DB2SIG/M.LBR (0E47), but the disk holds instead" "its expanded contents. OTOH, OAK/WC have DB2SIG/M.LBR" "(51C0) & matching -CATALOGs. No known extant ver of" "(0E47). Compares of CPMDOSGG files w/OAK LBR contents" "reveals significant CRC differences. I've chosen to" "go with OAK for this volume." ;;
    130) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    131) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    132) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    133) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    134) source cpmdosgg ; copyfiles; dismount; pad;                    rename "GLOBALS.RN_ GLOBALS.RN$" "PASZCODE.RN_ PASZCODE.RN$"     ; datefiles; archives; checkcrc ;;
    135) source cpmdosgg ; copyfiles; dismount; pad;                    rename "DIR_*"                                                   ; datefiles; archives; checkcrc  ; notes "TEST.SUB not in -CATALOG." ;;
    136) source cpmdosgg ; copyfiles; dismount; pad;                    rename "BB_*.*"                                                  ; datefiles; archives; checkcrc ;;
    137) source cpmdosgg ; copyfiles; dismount; pad;                    rename "MP_*"                     ; touch $builddir/MP-SIMUL.IN2 ; datefiles; archives; checkcrc  ; notes "-CATALOG lists a 0-byte MP-SIMUL.IN2, which is miss-" "ing from some collections. It is recreated here." ;;
    138) source cpmdosgg ; copyfiles; dismount; pad;                    rename "MP_DEMO.LBR MP-DEMO.LBR"                                 ; datefiles; archives; checkcrc ;;
    139) source cpmdosgg ; copyfiles; dismount; pad;                    rename "UN_PROT.BAS UN-PROT.BAS"                                 ; datefiles; archives; checkcrc ;;
    140) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    141) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    142) source cpmdosgg ; copyfiles; dismount; pad;                    rename "*_*" "SFA-SAV.0 SFA_SAV.0"                               ; datefiles; archives; checkcrc ;;
    143) source cpmdosgg ; copyfiles; dismount; pad;                    rename "PACKET_*"                                                ; datefiles; archives; checkcrc ;;
    144) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    145) source cpmdosgg ; copyfiles; dismount; pad;                    rename "*_*"                                                     ; datefiles; archives; checkcrc ;;
    146) source cpmdosgg ; copyfiles; dismount; pad;                    rename "SD_48B.A86 SD-48B.A86" "SD_48B.CMD SD-48B.CMD"           ; datefiles; archives; checkcrc ;;
    147) source cpmdosgg ; copyfiles; dismount; pad;                    rename "FILE_*" "CRCK_*" "WM_*"                                  ; datefiles; archives; checkcrc ;;
    148) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    149) source cpmdosgg ; copyfiles; dismount; pad;                    rename "MODEM7_*" "UNIX_*"                                       ; datefiles; archives; checkcrc ;;
    150) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    151) source cpmdosgg ; copyfiles; dismount; pad;                    rename "DSK7_*" "MBOOT_*" "FMT_*" "MODEM_*"                      ; datefiles; archives; checkcrc ;;
    152) source cpmdosgg ; copyfiles; dismount; pad;                    rename "DU_*.*"                                                  ; datefiles; archives; checkcrc ;;
    153) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    154) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    155) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc  ; notes "ABSTRACT.155 missing from all collections." ;;
    156) source cpmdosgg ; copyfiles; dismount; pad;                    rename "SQ_*"                                                    ; datefiles; archives; checkcrc ;;
    157) source cpmdosgg ; copyfiles; dismount; pad;                    rename "Z80_*"                                                   ; datefiles; archives; checkcrc ;;
    158) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    159) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    160) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    161) source cpmdosgg ; copyfiles; dismount; pad;                    rename "DU_*" "TYPER_*"                                          ; datefiles; archives; checkcrc ;;
    162) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    163) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    164) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc  ; notes "READTHIS not in -CATALOG." ;;
    165) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc  ; notes "READTHIS not in -CATALOG." ;;
    166) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc  ; notes "READTHIS not in -CATALOG." ;;
    167) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    168) source cpmdosgg ; copyfiles; dismount; pad;                    rename "*_*"                                                     ; datefiles; archives; checkcrc  ; notes "READTHIS not in -CATALOG." ;;
    169) source cpmdosgg ; copyfiles; dismount; pad;                    rename "M7*"                                                     ; datefiles; archives; checkcrc ;;
    170) source cpmdosgg ; copyfiles; dismount; pad;                    rename "M7*" "M7AC-3.AQM M7AC+3.AQM"                             ; datefiles; archives; checkcrc ;;
    171) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    172) source cpmdosgg ; copyfiles; dismount; pad;                    rename "DU_*" "OKI_*"                                            ; datefiles; archives; checkcrc ;;
    173) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc  ; notes "READTHIS not in -CATALOG." ;;
    174) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    175) source cpmdosgg ; copyfiles; dismount; pad;                    rename "F47_*" "MODEM_*"                                         ; datefiles; archives; checkcrc ;;
    176) source cpmdosgg ; copyfiles; dismount; pad;                    rename "DRI_*" "DU_*" "SD_*"                                     ; datefiles; archives; checkcrc ;;
    177) source cpmdosgg ; copyfiles; dismount; pad;                    rename "MY_*"; for i in $builddir/WS_*; do mv $i $(echo $i | tr '_' '$'); done ; datefiles; archives; checkcrc ;;
    178) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    179) source cpmdosgg ; copyfiles; dismount; pad;                    rename "BIOS3_.DQC BIOS3+.DQC"                                   ; datefiles; archives; checkcrc  ; notes "CARCHIVE.DQC not listed in -CATALOG." ;;
    180) source cpmdosgg ; copyfiles; dismount; pad;                    rename "*_*"                                                     ; datefiles; archives; checkcrc ;;
    181) source cpmdosgg ; copyfiles; dismount; pad;                    rename "*_*"                                                     ; datefiles; archives; checkcrc  ; notes "CXREF.HQP not listed in -CATALOG." ;;
    182) source cpmdosgg ; copyfiles; dismount; pad;                    rename "NS_*" "TAG_*"                                            ; datefiles; archives; checkcrc ;;
    183) source cpmdosgg ; copyfiles; dismount; pad;                    rename "READ_*"                                                  ; datefiles; archives; checkcrc ;;
    184) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    185) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    186) source cpmdosgg ; copyfiles; dismount; pad;                    rename "CRC_*"                                                   ; datefiles; archives; checkcrc ;;
    187) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    188) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    189) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    190) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    191) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    192) source cpmdosgg ; copyfiles; dismount; pad;                    rename "SYS2*"                                                   ; datefiles; archives; checkcrc ;;
    193) source cpmdosgg ; copyfiles; dismount; pad;                    rename "PAF*"                                                    ; datefiles; archives; checkcrc ;;
    194) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    195) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc  ; notes "-CATALOG mis-lists DELBR.COM as DELRB.COM." ;;
    196) source cpmdosgg ; copyfiles; dismount; pad;                    rename "SD_*"                                                    ; datefiles; archives; checkcrc ;;
    197) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc  ; notes "-CATALOG mis-lists DELBR.COM as DELIB.COM." ;;
    198) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    199) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    200) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    201) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    202) source cpmdosgg ; copyfiles; dismount; pad;                    rename "RSA_*"                                                   ; datefiles; archives; checkcrc ;;
    203) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    204) source cpmdosgg ; copyfiles; dismount; pad;                    rename "F83_*"                                                   ; datefiles; archives; checkcrc ;;
    205) source cpmdosgg ; copyfiles; dismount; pad;                    rename "F83_*"                                                   ; datefiles; archives; checkcrc ;;
    206) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    207) source cpmdosgg ; copyfiles; dismount; pad;                    rename "LU86_*" "APC_DUMP.LBR APC-DUMP.LBR"                      ; datefiles; archives; checkcrc ;;
    208) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    209) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    210) source cpmdosgg ; copyfiles; dismount; pad;                    rename "CRC_64.AQ6 CRC-64.AQ6"                                   ; datefiles; archives; checkcrc ;;
    211) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    212) source cpmdosgg ; copyfiles; dismount; pad; rename "CPM2__.LBR CPM2-+.LBR" "FIND_2.LBR FIND+2.LBR" "UNERA_.LBR UNERA+.LBR" "*_*"; datefiles; archives; checkcrc ;;
    213) source cpmdosgg ; copyfiles; dismount; pad;                    rename "LBR_*"                                                   ; datefiles; archives; checkcrc ;;
    214) source cpmdosgg ; copyfiles; dismount; pad;                    rename "LBR_*"                                                   ; datefiles; archives; checkcrc ;;
    215) source cpmdosgg ; copyfiles; dismount; pad;                    rename "LBR_*"                                                   ; datefiles; archives; checkcrc ;;
    216) source cpmdosgg ; copyfiles; dismount; pad;                    rename "M8NM_*"                                                  ; datefiles; archives; checkcrc ;;
    217) source cpmdosgg ; copyfiles; dismount; pad;                    rename "M8??_*"                                                  ; datefiles; archives; checkcrc ;;
    218) source cpmdosgg ; copyfiles; dismount; pad;                    rename "MX?_*"                                                   ; datefiles; archives; checkcrc ;;
    219) source cpmdosgg ; copyfiles; dismount; pad;                    rename "MX?_*"                                                   ; datefiles; archives; checkcrc ;;
    220) source cpmdosgg ; copyfiles; dismount; pad;                    rename "MX?_*" "MXO-R-10.AQM MXO-R+10.AQM"                       ; datefiles; archives; checkcrc ;;
    221) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    222) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    223) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    224) source cpmdosgg ; copyfiles; dismount; pad;                    rename "C80V_*"                                                  ; datefiles; archives; checkcrc ;;
    225) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    226) source cpmdosgg ; copyfiles; dismount; pad;                    rename "DRI_*"                                                   ; datefiles; archives; checkcrc ;;
    227) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    228) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    229) source cpmdosgg ; copyfiles; dismount; pad;                    rename "SAVE0_*" "APC_*"                                         ; datefiles; archives; checkcrc ;;
    230) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    231) source cpmdosgg ; copyfiles; dismount; pad;                    rename "CP_M_.LBR CP-M+.LBR"                                     ; datefiles; archives; checkcrc ;;
    232) source cpmdosgg ; copyfiles; dismount; pad;                    rename "M7BBS_.AQM M7BBS+.AQM"                                   ; datefiles; archives; checkcrc ;;
    233) source cpmdosgg ; copyfiles; dismount; pad;                    rename "BOY_*"                                                   ; datefiles; archives; checkcrc  ; notes "CLEANUP.DQC not listed in -CATALOG." ;;
    234) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    235) source cpmdosgg ; copyfiles; dismount; pad;                    rename "BOKA_EI.BQS BOKA&EI.BQS" "FORTH_*"                       ; datefiles; archives; checkcrc ;;
    236) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    237) source cpmdosgg ; copyfiles; dismount; pad;                    rename "PILOT_*"                                                 ; datefiles; archives; checkcrc ;;
    238) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    239) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    240) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc  ; notes "EPRINT.ZSM is unlisted in -CATALOG." ;;
    241) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    242) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    243) source oak      ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc  ; notes "CRC mismatch: GETNAME.PRO, VISCOS1 .DAT." ;;
    244) source cpmdosgg ; copyfiles; dismount; pad;                    rename "LPAK1?_*"                                                ; datefiles; archives; checkcrc ;;
    245) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    246) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    247) source cpmdosgg ; copyfiles; dismount; pad;                    rename "DU_*" "Z19_*"                                            ; datefiles; archives; checkcrc ;;
    248) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    249) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    250) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc  ; notes "Though VDO25.LBR is not listed in -CATALOG" "and seems out of place, it is retained.    " ;;
    251) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    252) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    253) source oak      ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    254) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    255) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    256) source cpmdosgg ; copyfiles; dismount; pad;                    rename "TFR_*" "TRANS_*"                                         ; datefiles; archives; checkcrc ;;
    257) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    258) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    259) source oak      ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    260) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    261) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    262) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    263) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    264) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    265) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    266) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    267) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    268) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    269) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    270) source cpmdosgg ; copyfiles; dismount; pad;                    rename "FS_*"                                                    ; datefiles; archives; checkcrc ;;
    271) source cpmdosgg ; copyfiles; dismount; pad;                    rename "FP_*"                                                    ; datefiles; archives; checkcrc ;;
    272) source cpmdosgg ; copyfiles; dismount; pad;                    rename "*_*"                                                     ; datefiles; archives; checkcrc ;;
    273) source cpmdosgg ; copyfiles; dismount; pad;                    rename "*_*"                                                     ; datefiles; archives; checkcrc ;;
    274) source cpmdosgg ; copyfiles; dismount; pad;                    rename "*_*"                                                     ; datefiles; archives; checkcrc ;;
    275) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    276) source cpmdosgg ; copyfiles; dismount; pad;                    rename "*_*"                                                     ; datefiles; archives; checkcrc ;;
    277) source cpmdosgg ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    278) source oak      ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    279) source oak      ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc  ; notes "LABEL.MAC, TAIL.ASM CRC mismatch." ;;
    280) source oak      ; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc  ; notes "MULTICOL.PAS CRC mismatch." ;;
    281) source sourdough; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc  ; notes "CRC mismatch: CMPCODE.DOC, ZLOAD.DOC," "SNOOPY.FOR, FORT07.DAT." ;;
    282) source sourdough; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    283) source sourdough; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    284) source sourdough; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    285) source sourdough; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc  ; notes "CRC mismatch: BROWSE.DOC, CURSOR.ASM," "SAVEREST.ASM, SAVEREST.DOC, TWENTY.ASM," "WORD-KEY.FIX.";;
    286) source sourdough; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    287) source sourdough; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    288) source sourdough; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    289) source sourdough; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc  ; notes "CRC mismatch: RAMDSKRB.DOC." ;;
    290) source sourdough; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    291) source sourdough; copyfiles; cp $src/../vol293/wipe.pas $builddir/WIPE.PAS; dismount; pad                                       ; datefiles; archives; checkcrc  ; notes "None of the extant sources yields matching" "CRCs. However, vol 293 has a good copy of " "WIPE.PAS; that is copied here.            " ;;
    292) source sourdough; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc  ; notes "CRC mismatch: SIZE.PAS, STRIP8.PAS." ;;
    293) source sourdough; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc  ; notes "WIPE.PAS not listed in -CATALOG." "Wandered over from v291?" ;;
    294) source sourdough; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    295) source sourdough; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    296) source sourdough; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    297) source sourdough; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    298) source sourdough; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    299) source sourdough; copyfiles; dismount; pad;                    rename "KPHANDYP.LBR KPHANDY+.LBR"                               ; datefiles; archives; checkcrc  ; notes "-READ.ME not listed in -CATALOG." ;;
    300) source sourdough; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    301) source sourdough; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    302) source sourdough; copyfiles; dismount; pad; remove CRCKLIST.CRC                                                                 ; datefiles; archives; checkcrc ;;
    303) source sourdough; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    304) source sourdough; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    305) source sourdough; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    306) source sourdough; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    307) source sourdough; copyfiles; dismount; pad; remove ./-READ.ME; rename "RDIR15P.LBR RDIR15+.LBR"                                 ; datefiles; archives; checkcrc ;;
    308) source sourdough; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    309) source sourdough; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
    310) source sourdough; copyfiles; dismount; pad                                                                                      ; datefiles; archives; checkcrc ;;
      *) echo Volume $vol not implemented yet. ;; # You should never see this.
  esac
  
#---------
# Clean up
#---------
  [[ -d $tempdir ]] && rm -rf $tempdir # in case it somehow got missed.
  cd - >/dev/null 2>&1
  
exit 0
